base_url = "https://gingeh.github.io"

title = "Gingeh's Stuff"
author = "Gingeh"

compile_sass = true
generate_feed = true

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"
render_emoji = true
